name: Run linters

on:
  push:
    branches:
      - 'master'
      - 'v*.*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install npm dependencies
        run: npm ci

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          eslint_dir: "src/javascripts"
          stylelint: true
          stylelint_dir: "src/sass"

      - name: Check build
        run: npm run build
